services:
  - type: web
    name: boat-rental
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://boating1.onrender.com
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-wandering-dew-azcjxici-pooler.c-3.ap-southeast-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: brms
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_auTExkB2zYP9
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DOMAIN
        value: ""
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: SESSION_SAME_SITE
        value: lax
      - key: SANCTUM_STATEFUL_DOMAINS
        value: boating1.onrender.com
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
      - key: MAIL_MAILER
        value: log
    healthCheckPath: /up
